apiVersion: v1
kind: Service
metadata:
  name: python-service
  namespace: backend
spec:
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: gcr.io/eco-tract-422800-r5/python-app:latest
        env:
        - name: DB_HOST
          value: "104.197.86.70"
        - name: DB_NAME
          value: "myappdb"
        - name: DB_USER
          value: "rama"
        - name: DB_PASSWORD
          value: "admin"
        ports:
        - containerPort: 5000