options:
  logging: CLOUD_LOGGING_ONLY  # Or use NONE if you do not want any logs

steps:
  # Build Docker images for the frontend and backend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/eco-tract-422800-r5/frontend-ui:latest', './frontend']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/eco-tract-422800-r5/python-app:latest', './backend']
  
  # Push images to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/eco-tract-422800-r5/frontend-ui:latest']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/eco-tract-422800-r5/python-app:latest']

  # Apply the deployments
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'backend.yaml']
    env: ['CLOUDSDK_COMPUTE_ZONE=us-central1-a', 'CLOUDSDK_CONTAINER_CLUSTER=gke-ramakrishna']
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'frontend.yaml']
    env: ['CLOUDSDK_COMPUTE_ZONE=us-central1-a', 'CLOUDSDK_CONTAINER_CLUSTER=gke-ramakrishna']
  
  # Deploy to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['set', 'image', 'deployment/frontend-ui', 'frontend-ui=gcr.io/eco-tract-422800-r5/frontend-ui:latest', '--namespace=frontend']
    env: ['CLOUDSDK_COMPUTE_ZONE=us-central1-a', 'CLOUDSDK_CONTAINER_CLUSTER=gke-ramakrishna']
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['set', 'image', 'deployment/python-app', 'python-app=gcr.io/eco-tract-422800-r5/python-app:latest', '--namespace=backend']
    env: ['CLOUDSDK_COMPUTE_ZONE=us-central1-a', 'CLOUDSDK_CONTAINER_CLUSTER=gke-ramakrishna']
