apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-ui
  namespace: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-ui
  template:
    metadata:
      labels:
        app: frontend-ui
    spec:
      containers:
      - name: frontend-ui
        image: gcr.io/eco-tract-422800-r5/frontend-ui:latest
        ports:
        - containerPort: 80